# Generated by Django 4.2.19 on 2025-04-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_data',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datamanages.st_company'),
        ),
    ]
