# Generated by Django 4.2.19 on 2025-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanages', '0002_alter_st_data_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_St_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
    ]
